<ul id="nav">
    <li><a href="#tab1" class="active">Manajemen Forum</a></li>
</ul>
<div class="clear"></div>
<div id="konten">
    <a href="#"><h6>Pengumuman Liburan</h6></a>

    <p style="float:left;">Penjelasan... Penjelasan... Penjelasan... Penjelasan... Penjelasan... Penjelasan...
        Penjelasan... Penjelasan... Penjelasan... Penjelasan... Penjelasan... Penjelasan... Penjelasan... Penjelasan...
        Penjelasan... Penjelasan... Penjelasan... Penjelasan... Penjelasan... Penjelasan... Penjelasan... Penjelasan...
        Penjelasan... Penjelasan... Penjelasan... Penjelasan... Penjelasan... Penjelasan... Penjelasan... Penjelasan...
        Penjelasan... Penjelasan... Penjelasan... Penjelasan...

    <p style="float:right; color:#03d"><a href="#">Selengkapnya...</a></p><br/><br/>


    <a href="#"><h6>Adanya sistem baru</h6></a>

    <p style="float:left;">Penjelasan... Penjelasan... Penjelasan... Penjelasan... Penjelasan... Penjelasan...
        Penjelasan... Penjelasan... Penjelasan... Penjelasan... Penjelasan... Penjelasan... Penjelasan... Penjelasan...
        Penjelasan... Penjelasan... Penjelasan... Penjelasan... Penjelasan... Penjelasan... Penjelasan... Penjelasan...
        Penjelasan... Penjelasan... Penjelasan... Penjelasan... Penjelasan... Penjelasan... Penjelasan... Penjelasan...
        Penjelasan... Penjelasan... Penjelasan... Penjelasan... </p><br/>

    <p style="float:right; color:#03d"><a href="#">Selengkapnya...</a></p><br/><br/>
</div>
</div>